name: work space build test 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        rosdistro:
          - jazzy

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Install dependencies
        run: |
          rosdep update && 
          apt-get update && 
          apt-get install -y git &&
          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}
      - name: Install diagnostic-updater
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive 

      - name: Build tests
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
